name: game_commerce_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-149.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  # Create bloc in flutter
  flutter_bloc: ^8.1.1
  # Create dependency injector in flutter
  get_it: ^7.2.0
  # Use for == operator
  equatable: ^2.0.5
  # Easily restart your application from scratch, losing any previous state
  flutter_phoenix: ^1.1.0
  # Use for localization instead of flutter_intl
  easy_localization: ^3.0.1
  # Use for animated splash effect
  animated_splash_screen: ^1.3.0
  # Use for navigation manager
  get: ^4.6.5
  # Use instead of share preference
  get_storage: ^2.0.3
  # A flutter plugin for adapting screen and font size.Guaranteed to look good on different models
  flutter_screenutil: ^5.5.4
  # A Flutter package to use fonts from fonts.google.com.
  google_fonts: ^3.0.1
  # An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
  flutter_svg: ^1.1.5
  # A carousel slider widget, support infinite scroll and custom child widget.
  carousel_slider: ^4.1.1
  # Flutter library to load and cache network images. Can also be used with placeholder and error widgets.
  cached_network_image: ^3.2.1
  # A collection of loading indicators animated with flutter. Heavily inspired by @tobiasahlin's SpinKit.
  flutter_spinkit: ^5.1.0
  # Flutter package that provides you custom clippers to help you achieve various custom shapes.
  flutter_custom_clippers: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1

flutter_icons:
  android: true
  ios: true
  min_sdk_android: 21
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#4B0560"
  adaptive_icon_foreground: "assets/icons/app_icon_512.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/app_icon_1024.png"
    background_color: "#4B0560"
    theme_color: "#4B0560"
  windows:
    generate: true
    image_path: "assets/icons/app_icon_1024.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
